// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhW20n-mPZBs6UO6PRhwJxyz711ehXeo',
    appId: '1:589420873783:web:df126c9d095456240057b2',
    messagingSenderId: '589420873783',
    projectId: 'sambank-academy',
    authDomain: 'sambank-academy.firebaseapp.com',
    databaseURL: 'https://sambank-academy-default-rtdb.firebaseio.com',
    storageBucket: 'sambank-academy.appspot.com',
    measurementId: 'G-K5K0P4YK5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68eGCk-6g1Zt4v1sFUS8ksIjFduFidZI',
    appId: '1:589420873783:android:842e9b13bca8c9b90057b2',
    messagingSenderId: '589420873783',
    projectId: 'sambank-academy',
    databaseURL: 'https://sambank-academy-default-rtdb.firebaseio.com',
    storageBucket: 'sambank-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeFsSsTpb4sPHRoiLW-31jeyFy78sp67U',
    appId: '1:589420873783:ios:77543e41353c0b8c0057b2',
    messagingSenderId: '589420873783',
    projectId: 'sambank-academy',
    databaseURL: 'https://sambank-academy-default-rtdb.firebaseio.com',
    storageBucket: 'sambank-academy.appspot.com',
    androidClientId: '589420873783-0sqh0o4s0mjq48o18m8ov991jmseum21.apps.googleusercontent.com',
    iosBundleId: 'com.example.elitepageTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeFsSsTpb4sPHRoiLW-31jeyFy78sp67U',
    appId: '1:589420873783:ios:e3ddfec4429951810057b2',
    messagingSenderId: '589420873783',
    projectId: 'sambank-academy',
    databaseURL: 'https://sambank-academy-default-rtdb.firebaseio.com',
    storageBucket: 'sambank-academy.appspot.com',
    androidClientId: '589420873783-0sqh0o4s0mjq48o18m8ov991jmseum21.apps.googleusercontent.com',
    iosBundleId: 'com.example.elitepageTwo.RunnerTests',
  );
}
